version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-29

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx2048m
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError" -Dorg.gradle.parallel=true -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          key: gradle-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle" }}-{{ checksum "buildSrc/src/main/kotlin/Dependencies.kt" }}

      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle/caches
          key: gradle-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle" }}-{{ checksum "buildSrc/src/main/kotlin/Dependencies.kt" }}

      - run:
          name: Gradle build
          command: ./gradlew clean assembleDebug testNoapiDebugUnitTest testPinboardapiDebugUnitTest
