name: Android CI

on:
  push:
    branches:
      - '**'

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Project Checkout
        uses: actions/checkout@v2.3.2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Gradle Wrapper Cache
        uses: actions/cache@v2.1.1
        id: gradle-wrapper-cache
        with:
          path: ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-

      - name: Gradle Cache
        uses: actions/cache@v2.1.1
        id: gradle-cache
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('buildSrc/src/main/kotlin/Dependencies.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - run: .github/scripts/gradlew_recursive.sh androidDependencies
        if: steps.gradle-wrapper-cache.outputs.cache-hit != 'true' || steps.gradle-cache.outputs.cache-hit != 'true'

      - name: Run Tests
        run: .github/scripts/gradlew_recursive.sh clean testPinboardapiDebugUnitTest --stacktrace

      - name: Upload Test Reports
        uses: actions/upload-artifact@v2
        with:
          path: app/build/reports/tests/

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Project Checkout
        uses: actions/checkout@v2.3.2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Gradle Wrapper Cache
        uses: actions/cache@v2.1.1
        id: gradle-wrapper-cache
        with:
          path: ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-

      - name: Gradle Cache
        uses: actions/cache@v2.1.1
        id: gradle-cache
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('buildSrc/src/main/kotlin/Dependencies.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - run: .github/scripts/gradlew_recursive.sh androidDependencies
        if: steps.gradle-wrapper-cache.outputs.cache-hit != 'true' || steps.gradle-cache.outputs.cache-hit != 'true'

      - name: Build
        run: .github/scripts/gradlew_recursive.sh clean assemblePinboardapi --stacktrace

      - name: Upload Pinboard API APK
        uses: actions/upload-artifact@v2
        with:
          path: app/build/outputs/apk/pinboardapi/debug/app-pinboardapi-debug.apk

  instrumented_tests:
    name: Instrumented Tests
    runs-on: macOS-latest
    needs: [unit_tests, build]
    steps:
      - name: Project Checkout
        uses: actions/checkout@v2.3.2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Gradle Wrapper Cache
        uses: actions/cache@v2.1.1
        id: gradle-wrapper-cache
        with:
          path: ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-

      - name: Gradle Cache
        uses: actions/cache@v2.1.1
        id: gradle-cache
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('buildSrc/src/main/kotlin/Dependencies.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - run: .github/scripts/gradlew_recursive.sh androidDependencies
        if: steps.gradle-wrapper-cache.outputs.cache-hit != 'true' || steps.gradle-cache.outputs.cache-hit != 'true'

      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2.11.0
        with:
          api-level: 29
          arch: x86_64
          script: .github/scripts/gradlew_recursive.sh clean :app:connectedAndroidTest --stacktrace
